### ISSUE TITLE
Naming Options

### ISSUE THREAD

**Issue by hahnryu** [eoscostarica/no-vote-buy-EOS-proxy#47]
Hey EOS Costa Rica,

I first have to say that I thank you so much for your time and effort you all have committed so far for this initiative.

Since the moment we have first invited you to create this website, the initial concept of the whole scheme of this campaign has also evolved, with more consideration for nuanced political implication this project will communicate with its language and design. 

The ultimate bottle neck was the branding/naming issue, because it will define all the narrative and context, while #novotebuy campaign brand might change later, the name of proxy will have to stay even after. There has been juggling around a few naming options, but I think we're likely to go with campaign name of "#novotebuyeos" with the proxy account name of "onedaoforall". (because it will represent so much people's uncompromised voice from all around the community, and for not using EOS brand in the proxy account name is because there's a slight chance of EOS re-branding into something else.

* BP selecting criteria PDF is 90% done.
* The exact language change suggestion on Figma will be shared in a separate doc by this weekend, as all docs and languages gets final and done with brand/name finalization.
* Google form for proxy signup will be provided as well upon I share the Figma suggestion and BP criteria PDF.
* I'll secure account onedaoforall, onedaoforeos, onedaoforkor on EOS mainnet and share the key.
* Getting Twitter API key is harder than I thought, I'll update as soon as I get it.
* Waxa & Creamer will be in charge of social channels and contents.

Cheers,
Hahn

**Comment by xavier506** [comment]
@hahnryu  thank you for the information and updates and all your hard work!

**Comment by xavier506** [comment]
do we have more clarityon the name / branding we will use for this project ?

**Comment by xavier506** [comment]
![image](https://user-images.githubusercontent.com/5632966/153243074-5024e969-ddaf-4b89-91bc-300b811ae31e.png)
